"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { api, formatDate, friendlyError, type MemberDocument, type Registration } from "@/lib/membershipApi";

type Props = {
  registration: Registration;
  token: string;
  onSignOut: () => void;
  onAuthError: (err: unknown) => boolean;
};

const DOC_LABELS: Record<string, { title: string; text: string }> = {
  receipt: { title: "Payment receipt", text: "Proof of your membership fee payment." },
  membership_letter: { title: "Membership letter", text: "Your official welcome letter with your membership ID." },
};

const POLL_MS = 4000;
const POLL_LIMIT_MS = 120_000;

export default function SuccessStep({ registration, token, onSignOut, onAuthError }: Props) {
  const [docs, setDocs] = useState<MemberDocument[] | null>(null);
  const [waitingTooLong, setWaitingTooLong] = useState(false);
  const [downloading, setDownloading] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const timer = useRef<number | undefined>(undefined);
  const mounted = useRef(true);

  useEffect(() => () => { mounted.current = false; window.clearTimeout(timer.current); }, []);

  /** Documents are generated by the backend worker after activation; wait until they're ready. */
  const load = useCallback(async (startedAt = Date.now()) => {
    try {
      const status = await api.paymentStatus(token);
      if (status.documents_ready) {
        const list = await api.documents(token);
        if (mounted.current) { setDocs(list); setWaitingTooLong(false); }
        return;
      }
    } catch (err) {
      if (onAuthError(err)) return;
    }
    if (!mounted.current) return;
    if (Date.now() - startedAt > POLL_LIMIT_MS) { setWaitingTooLong(true); return; }
    timer.current = window.setTimeout(() => load(startedAt), POLL_MS);
  }, [token, onAuthError]);

  useEffect(() => { load(); }, [load]);

  const download = async (doc: MemberDocument) => {
    setError(null);
    setDownloading(doc.id);
    try {
      await api.downloadDocument(token, doc);
    } catch (err) {
      if (!onAuthError(err)) setError(friendlyError(err));
    } finally {
      setDownloading(null);
    }
  };

  const firstName = registration.full_name.split(/\s+/)[0];

  return (
    <div className="success">
      <div className="success__seal" aria-hidden="true">
        <svg viewBox="0 0 64 64"><path className="flame" d="M32 6c6 9 9 15 9 20a9 9 0 0 1-18 0c0-5 3-11 9-20z" /><path d="M6 38h52c-3 11-13 18-26 18S9 49 6 38z" /></svg>
      </div>
      <p className="success__eyebrow">॥ स्वागतम् ॥</p>
      <h2>Welcome to the family, {firstName}!</h2>
      <p className="success__lead">Your membership of Shree Dharmic Leela is active. Thank you for being part of the journey.</p>

      <div className="member-card">
        <div>
          <span className="member-card__label">Membership ID</span>
          <strong className="member-card__id">{registration.membership_id}</strong>
        </div>
        <div className="member-card__meta">
          <span><em>Name</em>{registration.full_name}</span>
          {registration.membership_activated_at && <span><em>Member since</em>{formatDate(registration.membership_activated_at)}</span>}
        </div>
      </div>

      <section className="docs" aria-labelledby="docs-title">
        <h3 id="docs-title">Your documents</h3>
        {error && <p className="form-error" role="alert">{error}</p>}

        {!docs && !waitingTooLong && (
          <div className="status-box" role="status">
            <span className="spinner" />
            <div><strong>Preparing your receipt and membership letter…</strong><span>This takes a few moments.</span></div>
          </div>
        )}
        {!docs && waitingTooLong && (
          <div className="status-box status-box--info" role="status">
            <div><strong>Your documents are taking longer than usual</strong><span>They&apos;ll also be sent to {registration.email}. You can check again here any time.</span></div>
            <button type="button" className="btn btn--outline btn--sm" onClick={() => { setWaitingTooLong(false); load(); }}>Check again</button>
          </div>
        )}

        {docs && (
          <ul className="doc-list">
            {docs.map((d) => {
              const label = DOC_LABELS[d.document_type] ?? { title: d.filename, text: "" };
              const ready = d.status === "generated";
              return (
                <li key={d.id} className="doc">
                  <span className="doc__icon" aria-hidden="true">
                    <svg viewBox="0 0 24 24"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z" /><path d="M14 3v5h5M9 13h6M9 17h4" /></svg>
                  </span>
                  <div className="doc__text">
                    <strong>{label.title}</strong>
                    <span>{ready ? `${label.text} PDF${d.size_bytes ? ` · ${Math.max(1, Math.round(d.size_bytes / 1024))} KB` : ""}` : d.status === "failed" ? "Couldn't be generated. Please contact the committee." : "Being prepared…"}</span>
                  </div>
                  <button type="button" className="btn btn--outline btn--sm" disabled={!ready || downloading === d.id} onClick={() => download(d)}>
                    {downloading === d.id ? <><span className="spinner" /> Downloading…</> : <><DownloadIcon /> Download</>}
                  </button>
                </li>
              );
            })}
          </ul>
        )}
      </section>

      <div className="success__actions">
        <a href="/" className="btn btn--primary">Back to home</a>
        <button type="button" className="link-btn" onClick={onSignOut}>Sign out on this device</button>
      </div>
    </div>
  );
}

function DownloadIcon() {
  return <svg className="btn-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 4v11M7 10l5 5 5-5M5 20h14" /></svg>;
}
